//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDomino
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int idGame { get; set; }
        public string playerOne { get; set; }
        public string playerTwo { get; set; }
        public string dateGame { get; set; }
        public string status { get; set; }
        public string result { get; set; }
    }
}
