//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDomino.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfDomino.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandon Game.
        /// </summary>
        public static string btAbandonGame {
            get {
                return ResourceManager.GetString("btAbandonGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string btCancel {
            get {
                return ResourceManager.GetString("btCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click Here.
        /// </summary>
        public static string btClickHere {
            get {
                return ResourceManager.GetString("btClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string btConfirm {
            get {
                return ResourceManager.GetString("btConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display History.
        /// </summary>
        public static string btDisplayHistory {
            get {
                return ResourceManager.GetString("btDisplayHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Game.
        /// </summary>
        public static string btJoinGame {
            get {
                return ResourceManager.GetString("btJoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave.
        /// </summary>
        public static string btLeave {
            get {
                return ResourceManager.GetString("btLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave Game.
        /// </summary>
        public static string btLeaveGame {
            get {
                return ResourceManager.GetString("btLeaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string btLogin {
            get {
                return ResourceManager.GetString("btLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pass Turn.
        /// </summary>
        public static string btPassTurn {
            get {
                return ResourceManager.GetString("btPassTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place Token.
        /// </summary>
        public static string btPlaceToken {
            get {
                return ResourceManager.GetString("btPlaceToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string btSavePlayer {
            get {
                return ResourceManager.GetString("btSavePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Email.
        /// </summary>
        public static string btSendEmail {
            get {
                return ResourceManager.GetString("btSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sing Off.
        /// </summary>
        public static string btSingOff {
            get {
                return ResourceManager.GetString("btSingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Star Game.
        /// </summary>
        public static string btStarGame {
            get {
                return ResourceManager.GetString("btStarGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Board Color: .
        /// </summary>
        public static string lbBoardColor {
            get {
                return ResourceManager.GetString("lbBoardColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code:.
        /// </summary>
        public static string lbCode {
            get {
                return ResourceManager.GetString("lbCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Game.
        /// </summary>
        public static string lbCreateGame {
            get {
                return ResourceManager.GetString("lbCreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email:.
        /// </summary>
        public static string lbEmail {
            get {
                return ResourceManager.GetString("lbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games Loses: .
        /// </summary>
        public static string lbGamesLose {
            get {
                return ResourceManager.GetString("lbGamesLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games Total: .
        /// </summary>
        public static string lbGamesTotal {
            get {
                return ResourceManager.GetString("lbGamesTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games Wins: .
        /// </summary>
        public static string lbGamesWins {
            get {
                return ResourceManager.GetString("lbGamesWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you are not registered yet.
        /// </summary>
        public static string lbMessageRecord {
            get {
                return ResourceManager.GetString("lbMessageRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name:.
        /// </summary>
        public static string lbName {
            get {
                return ResourceManager.GetString("lbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password:.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview: .
        /// </summary>
        public static string lbPreview {
            get {
                return ResourceManager.GetString("lbPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration.
        /// </summary>
        public static string lbRegistration {
            get {
                return ResourceManager.GetString("lbRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User: .
        /// </summary>
        public static string lbUser {
            get {
                return ResourceManager.GetString("lbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UserName:.
        /// </summary>
        public static string lbUserName {
            get {
                return ResourceManager.GetString("lbUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome: .
        /// </summary>
        public static string lbWelcome {
            get {
                return ResourceManager.GetString("lbWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Board.
        /// </summary>
        public static string titleBoard {
            get {
                return ResourceManager.GetString("titleBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consult History.
        /// </summary>
        public static string titleCosultHistory {
            get {
                return ResourceManager.GetString("titleCosultHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string titleLogin {
            get {
                return ResourceManager.GetString("titleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record Player.
        /// </summary>
        public static string titleRecordPlayer {
            get {
                return ResourceManager.GetString("titleRecordPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Game.
        /// </summary>
        public static string titleStartGame {
            get {
                return ResourceManager.GetString("titleStartGame", resourceCulture);
            }
        }
    }
}
